### ISSUE TITLE
Specifying an alias in cfquery shows attribute suggestion list

### ISSUE THREAD

**Issue by jcush** [zoo1/autocomplete-cfml#4]
When populating a CFQuery, aliases cause an attribute suggestion list to appear.

When using field aliases:
![image](https://cloud.githubusercontent.com/assets/10184859/20883109/41ff36ea-badc-11e6-869f-def952d942bb.png)

When using table aliases:
![image](https://cloud.githubusercontent.com/assets/10184859/20883131/68bf5378-badc-11e6-8d70-642f14433ef5.png)

**Comment by zoo1** [comment]
@jcush this has been resolved in version 0.3.0 . I introduced a feature called limited scopes which makes autocomplete a lot more conservative inside of cfquery, embedded js, and embedded css. Let me know what your thoughts are!

**Comment by jcush** [comment]
Can't re-open, but this doesn't seem to be fixed unfortunately. Updated to 0.3 and restarted Atom, but still getting the same issue:

![image](https://cloud.githubusercontent.com/assets/10184859/21051471/4c96e636-be18-11e6-963c-767a865c485a.png)
![image](https://cloud.githubusercontent.com/assets/10184859/21051480/576199e4-be18-11e6-9b3a-67b18a60ff4b.png)

Cheers

**Comment by zoo1** [comment]
@jcush To give the full details of the solution. Since the alias don't have any scopes to sniff off, there isn't an easy solution for this. To completely disable autocomplete inside of cfquery/css/js wouldn't be optimal. Currently I'm just matching just agains't the CFML control tags and cfqueryparam, but it seems like that is even too much. I'll revisit this after functions are released and reevaluate.

**Comment by jcush** [comment]
Hmm, I do see your issue. I'm not sure how you're capturing the preceding text to the cursor, but maybe there's a rule somewhere in the number of space-delimited strings on a line. However, then you hit the problem of how different developers format their queries. I use new lines when others may not.

Maybe it's a case of looking at how many of these tokens (if you could call a string surrounded by spaces as a 'token') are between the cursor and the nearest SQL keyword.

e.g. FROM {x} {y} - here, the autocomplete should suppress on reaching 'y', which is the next-but-one 'token' after the SQL keyword. Extending, though, you would have to further group by use of the comma, since you might select from multiple tables which are all aliased (as unlikely as this would be). 

I feel like the field names one would be easier due to its use of the AS keyword to check against (if the current 'token' is straight after 'AS', then suppress).

I'd be happy to help with this if you need me to at some stage.

UPDATE: Within a cfquery, maybe cfqueryparam is the only string you need to autocomplete on anywway? In this case, you could just reveal the autocomplete list on receiving "<cf" within the cfquery block

**Comment by zoo1** [comment]
@jcush your update is the method I was thinking.

**Comment by jcush** [comment]
Seems to be the simplest way. 

Have you ever thought about adding CFScript support to this too? I do quite a bit of work with the CFScript now, almost more than tag syntax so would benefit from this. Happy to contribute if necessary. Would have messaged you about this separately but there seems to be no PM system on GitHub

**Comment by zoo1** [comment]
@jcush CFScript support was planned down the road. Any contributions are welcome! If you want to PM me you can reach me over email(zacharyovington@gmail.com).

**Comment by zoo1** [comment]
A better fix for this has been pushed in 0.4.1, which requires the autocomplete to be prepended with 'cf' + additional characters before it will show up.
